In [40]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
# Load the dataset
california = fetch_california_housing()

# part 1

In [41]:
# q1
df = pd.DataFrame(data = california.data, columns=california.feature_names)

df['MedHouseVal'] = california.target
df.head()
df.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='str')

In [42]:
#q2
df.head(7)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992

In [43]:
#q3
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [44]:
#q4
df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

# part 2

In [45]:
#q5
df[['MedInc','MedInc','MedHouseVal']].head(15)

    MedInc  MedInc  MedHouseVal
0   8.3252  8.3252        4.526
1   8.3014  8.3014        3.585
2   7.2574  7.2574        3.521
3   5.6431  5.6431        3.413
4   3.8462  3.8462        3.422
5   4.0368  4.0368        2.697
6   3.6591  3.6591        2.992
7   3.1200  3.1200        2.414
8   2.0804  2.0804        2.267
9   3.6912  3.6912        2.611
10  3.2031  3.2031        2.815
11  3.2705  3.2705        2.418
12  3.0750  3.0750        2.135
13  2.6736  2.6736        1.913
14  1.9167  1.9167        1.592

In [46]:
#q6
filter = df[(df['HouseAge'] > 35) & (df['MedInc'] > 6.0)]
print(len(filter))

525

In [47]:
#q7
q7 = df.iloc[100:121, 0:4]
print(q7)

     MedInc  HouseAge  AveRooms  AveBedrms
100  2.4912      29.0  3.724800   1.131200
101  3.2177      28.0  3.878424   1.070808
102  3.1250      39.0  3.745614   1.061404
103  2.5795      52.0  3.515498   1.143556
104  2.8406      34.0  3.281722   1.069871
105  4.9306      52.0  6.184426   0.922131
106  3.2727      52.0  4.442982   1.057018
107  3.1691      52.0  4.165877   1.090047
108  3.9000      52.0  4.848189   1.045961
109  3.9063      28.0  4.160848   1.066085
110  5.0917      52.0  5.628458   1.142292
111  2.6429      32.0  3.727006   1.074364
112  3.0233      26.0  3.253081   0.982744
113  3.1484      52.0  4.578035   1.077071
114  3.4722      35.0  3.822275   1.014218
115  3.1429      52.0  4.395189   0.986254
116  2.4234      28.0  3.023480   1.053582
117  3.0897      52.0  4.040501   1.065574
118  5.8596      50.0  6.742627   1.069705
119  5.2868      47.0  6.546392   0.936082
120  5.9560      41.0  6.851064   1.079787

In [57]:
#q8 
maxVal = df['MedHouseVal'].idxmax()
maxHouseRow = df.loc[maxVal]
print(maxHouseRow)
print(f"Population -> {maxHouseRow['Population']}")

MedInc           1.243400
HouseAge        52.000000
AveRooms         2.929412
AveBedrms        0.917647
Population     396.000000
AveOccup         4.658824
Latitude        37.800000
Longitude     -122.270000
MedHouseVal      5.000010
Name: 89, dtype: float64
Population -> 396.0