In [54]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
# Load the dataset
california = fetch_california_housing()

In [55]:
# q1
df = pd.DataFrame(data = california.data, columns=california.feature_names)

df['MedHouseVal'] = california.target
df.head()
df.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='str')

In [56]:
#q2
df.head(7)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992

In [57]:
#q3
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [58]:
#q4
df.describe().T

,count,mean,std,min,25%,50%,75%,max
MedInc,20640.0,3.870671,1.899822,0.499900,2.563400,3.534800,4.743250,15.000100
HouseAge,20640.0,28.639486,12.585558,1.000000,18.000000,29.000000,37.000000,52.000000
AveRooms,20640.0,5.429000,2.474173,0.846154,4.440716,5.229129,6.052381,141.909091
AveBedrms,20640.0,1.096675,0.473911,0.333333,1.006079,1.048780,1.099526,34.066667
Population,20640.0,1425.476744,1132.462122,3.000000,787.000000,1166.000000,1725.000000,35682.000000
AveOccup,20640.0,3.070655,10.386050,0.692308,2.429741,2.818116,3.282261,1243.333333
Latitude,20640.0,35.631861,2.135952,32.540000,33.930000,34.260000,37.710000,41.950000
Longitude,20640.0,-119.569704,2.003532,-124.350000,-121.800000,-118.490000,-118.010000,-114.310000
MedHouseVal,20640.0,2.068558,1.153956,0.149990,1.196000,1.797000,2.647250,5.000010

In [59]:
#q5
df[['MedInc','MedInc','MedHouseVal']].head(15)

    MedInc  MedInc  MedHouseVal
0   8.3252  8.3252        4.526
1   8.3014  8.3014        3.585
2   7.2574  7.2574        3.521
3   5.6431  5.6431        3.413
4   3.8462  3.8462        3.422
5   4.0368  4.0368        2.697
6   3.6591  3.6591        2.992
7   3.1200  3.1200        2.414
8   2.0804  2.0804        2.267
9   3.6912  3.6912        2.611
10  3.2031  3.2031        2.815
11  3.2705  3.2705        2.418
12  3.0750  3.0750        2.135
13  2.6736  2.6736        1.913
14  1.9167  1.9167        1.592

In [60]:
#q6
filter = df[(df['HouseAge'] > 35) & (df['MedInc'] > 6.0)]
print(len(filter))

525

In [61]:
#q7
q7 = df.iloc[100:121, 0:4]
print(q7)

     MedInc  HouseAge  AveRooms  AveBedrms
100  2.4912      29.0  3.724800   1.131200
101  3.2177      28.0  3.878424   1.070808
102  3.1250      39.0  3.745614   1.061404
103  2.5795      52.0  3.515498   1.143556
104  2.8406      34.0  3.281722   1.069871
105  4.9306      52.0  6.184426   0.922131
106  3.2727      52.0  4.442982   1.057018
107  3.1691      52.0  4.165877   1.090047
108  3.9000      52.0  4.848189   1.045961
109  3.9063      28.0  4.160848   1.066085
110  5.0917      52.0  5.628458   1.142292
111  2.6429      32.0  3.727006   1.074364
112  3.0233      26.0  3.253081   0.982744
113  3.1484      52.0  4.578035   1.077071
114  3.4722      35.0  3.822275   1.014218
115  3.1429      52.0  4.395189   0.986254
116  2.4234      28.0  3.023480   1.053582
117  3.0897      52.0  4.040501   1.065574
118  5.8596      50.0  6.742627   1.069705
119  5.2868      47.0  6.546392   0.936082
120  5.9560      41.0  6.851064   1.079787

In [62]:
#q8 
maxVal = df['MedHouseVal'].idxmax()
maxHouseRow = df.loc[maxVal]
print(maxHouseRow)
print(f"Population -> {maxHouseRow['Population']}")

MedInc           1.243400
HouseAge        52.000000
AveRooms         2.929412
AveBedrms        0.917647
Population     396.000000
AveOccup         4.658824
Latitude        37.800000
Longitude     -122.270000
MedHouseVal      5.000010
Name: 89, dtype: float64
Population -> 396.0

In [63]:
#q9
df.loc[:49, "AveBedrms"]=np.nan
print(df["AveBedrms"].isnull().sum())

50

In [64]:
#q10
medianValue = df["AveBedrms"].median()
df["AveBedrms"] = df["AveBedrms"].fillna(medianValue)
print(df["AveBedrms"].isnull().sum())

0

In [65]:
#q11
df = pd.concat([df,df.head(5)],ignore_index=True)
duplicatesRows = df.duplicated().sum()
print(f"Duplicate rows = {duplicatesRows}")

df = df.drop_duplicates(ignore_index=True)
print(f"After droping = {df.duplicated().sum()}")

Duplicate rows = 5
After droping = 0

In [66]:
#12
df["HouseAge"] = df["HouseAge"].mask(df["HouseAge"] > 40 , 40.0 )

print(f"max house age = {df["HouseAge"].max()}")

max house age = 40.0

In [67]:
#q13
catagoryAge = [0,15,30,100]
Catagorylabels = ["New","Established","Hostoric"]
df["AgeCategory"] = pd.cut(df["HouseAge"],bins=catagoryAge,labels=Catagorylabels)

print(df["AgeCategory"].value_counts())

AgeCategory
Hostoric       9495
Established    7858
New            3287
Name: count, dtype: int64

In [68]:
#Q14
grouped_df = (
    df.groupby("AgeCategory", observed=False)[["MedHouseVal", "MedInc"]]
    .mean()
)

print(grouped_df)

             MedHouseVal    MedInc
AgeCategory
New             1.922335  4.296516
Established     2.021997  3.913671
Hostoric        2.157712  3.687665

In [69]:
#q15
pivotTable = pd.pivot_table(
    df,
    values="Population",
    index="AgeCategory",
    aggfunc="max",
    observed=False,
)

print(pivotTable)

             Population
AgeCategory
New             35682.0
Established     12427.0
Hostoric         9879.0

In [70]:
#16
age_freq_table = pd.crosstab(
    index=df["AgeCategory"], 
    columns="Count", 
    colnames=[""]
)
print(age_freq_table)

             Count
AgeCategory
New           3287
Established   7858
Hostoric      9495

In [71]:
#17
df["Rooms_per_Occupant"] = df["AveRooms"] / df["AveOccup"]
print(df[["AveRooms", "AveOccup", "Rooms_per_Occupant"]].head())

   AveRooms  AveOccup  Rooms_per_Occupant
0  6.984127  2.555556            2.732919
1  6.238137  2.109842            2.956685
2  8.288136  2.802260            2.957661
3  5.817352  2.547945            2.283154
4  6.281853  2.181467            2.879646

In [72]:
#18
mean_inc = df["MedInc"].mean()
std_inc = df["MedInc"].std()
df["MedInc_Standardized"] = (df["MedInc"] - mean_inc) / std_inc
print("Standardized Mean:", round(df["MedInc_Standardized"].mean(), 4))
print("Standardized Std:", round(df["MedInc_Standardized"].std(), 4))

Standardized Mean: 0.0
Standardized Std: 1.0

In [73]:
#19
df["Is_Expensive"] = (df["MedHouseVal"] > 3.0).astype(int)
print(df["Is_Expensive"].value_counts())

Is_Expensive
0    16804
1     3836
Name: count, dtype: int64

In [74]:
#20
df = df.sort_values(by="Longitude", ascending=True).reset_index(drop=True)
df["Spatial_Rolling_Price"] = (
    df["MedHouseVal"].rolling(window=5).mean()
)
print(df[["Longitude", "MedHouseVal", "Spatial_Rolling_Price"]].head(10))

   Longitude  MedHouseVal  Spatial_Rolling_Price
0    -124.35        0.946                    NaN
1    -124.30        0.858                    NaN
2    -124.30        1.036                    NaN
3    -124.27        0.790                    NaN
4    -124.26        1.114                 0.9488
5    -124.25        0.761                 0.9118
6    -124.23        0.732                 0.8866
7    -124.23        0.508                 0.7810
8    -124.23        1.067                 0.8364
9    -124.22        0.783                 0.7702